#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#


library(shiny)
library(saasCNV)

data(seq.data)
data(seq.cnv)

# Define UI for application that draws a histogram
ui <- fluidPage(
  
  # Application title
  titlePanel("function: snp.refine.boundary"),
  
  # Sidebar with a slider input for number of bins 
  sidebarPanel(
    textInput("data",
              label = "a data frame containing log2ratio and log2mBAF data generated by snp.cnv.data.",
              value = "snp.data.RData"),
    textInput("segs.stat",
              label = "a data frame containing segment locations and summary statistics resulting from cnv.call.",
              value = "cnv.call")
  ),
  
  # Show a plot of the generated distribution
  mainPanel(
    h3(textOutput("caption")), 
    tableOutput("res")
  )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
  text <- reactive({
    paste("hi",input$data)
  })
  
  load("snp.data.RData")
  data(snp.cnv)
  snp.cnv.refine <- snp.refine.boundary(data=snp.data, segs.stat=snp.cnv)
  data(snp.cnv.refine)
  
  output$res <- renderTable(
    head(snp.cnv.refine)
  )
}

# Run the application 
shinyApp(ui = ui, server = server)

